#!/usr/bin/env bash
# Bash script displays DNS records: record type, IP, subdomainfunc () {
if [ "$#" -lt 1 ]
then
exit 0
elif [ "$#" -eq 2 ]
then
domain=$2.$1
name=$(dig $domain | grep -A1 'ANSWER SECTION:' | awk -F. 'NR==2 {print $1}')
record=$(dig $domain  | grep -A1 'ANSWER SECTION:' | awk 'NR==2 {print $4}')
ip=$(dig $domain  | grep -A1 'ANSWER SECTION:' | awk 'NR==2 {print $5}')
echo "The subdomain $name is a $record record and points to $ip"
else
declare -a arr=("www" "lb-01" "web-01" "web-02")
for i in "${arr[@]}"
do
domain=$i.$1
name=$(dig $domain | grep -A1 'ANSWER SECTION:' | awk -F. 'NR==2 {print $1}')
record=$(dig $domain  | grep -A1 'ANSWER SECTION:' | awk 'NR==2 {print $4}')
ip=$(dig $domain  | grep -A1 'ANSWER SECTION:' | awk 'NR==2 {print $5}')
echo "The subdomain $name is a $record record and points to $ip"
done
fi
}
func $1 $2
